config/routes.rb
Rails.application.routes.draw do

  get 'editor_index' => 'articles#editor_index'

  resources :players

  resources :teams

  root :to => 'articles#index'

  resources :articles

  devise_for :users

  get 'users/sign_out' => 'users#sign_out'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.publisher?
      can :manage, :all
    elsif user.editor?
      can :manage, Article
    else
      can :read, :all
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base

	belongs_to :team
	belongs_to :player

end

app/models/player.rb
class Player < ActiveRecord::Base

	belongs_to :team
	has_many :articles

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
 	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/team.rb
class Team < ActiveRecord::Base

	has_many :players
	has_many :articles

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :parental_approval, :editor, :publisher) }
		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :name, :parental_approval, :editor, :publisher) }
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  respond_to :html

  before_filter :authenticate_user!

  def index
    @articles = Article.all
    respond_with(@articles)
  end

  def editor_index
    @articles = Article.all
    respond_with(@articles)
  end



# *******************************************
# RANDOMIZE ANSWER DISPLAY
# *******************************************

  def show
    @randomize_answers1 = []
    @randomize_answers1.push(@article.q1answer)
    @randomize_answers1.push(@article.q1wrong1) 
    @randomize_answers1.push(@article.q1wrong2) 

    @randomize_answers2 = []
    @randomize_answers2.push(@article.q2answer)
    @randomize_answers2.push(@article.q2wrong1) 
    @randomize_answers2.push(@article.q2wrong2) 

    @randomize_answers3 = []
    @randomize_answers3.push(@article.q3answer)
    @randomize_answers3.push(@article.q3wrong1) 
    @randomize_answers3.push(@article.q3wrong2)

    respond_with(@article)
  end

  def new
    @players = Player.all
    @teams = Team.all
    @article = Article.new
    respond_with(@article)
  end

  def edit
    @players = Player.all
    @teams = Team.all
  end

  def create
    @article = Article.new(article_params)
    @article.save
    respond_with(@article)
  end

  def update
    @article.update(article_params)
    respond_with(@article)
  end

  def destroy
    @article.destroy
    respond_with(@article)
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:publishable, :video, :part1, :quiz1, :q1answer, :q1wrong1, :q1wrong2, :part2, :quiz2, :q2answer, :q2wrong1, :q2wrong2, :part3, :quiz3, :q3answer, :q3wrong1, :q3wrong2, :team_id, :player_id)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  authorize_resource :class => false

  respond_to :html

  def index
    @players = Player.all
    respond_with(@players)
  end

  def show
    respond_with(@player)
  end

  def new
    @teams = Team.all
    @player = Player.new
    respond_with(@player)
  end

  def edit
    @teams = Team.all
  end

  def create
    @player = Player.new(player_params)
    @player.save
    respond_with(@player)
  end

  def update
    @player.update(player_params)
    respond_with(@player)
  end

  def destroy
    @player.destroy
    respond_with(@player)
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:name, :team_id, :article_id, :goals, :avatar)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  authorize_resource :class => false

  respond_to :html

  def index
    @teams = Team.all
    respond_with(@teams)
  end

  def show
    respond_with(@team)
  end

  def new
    @team = Team.new
    respond_with(@team)
  end

  def edit
  end

  def create
    @team = Team.new(team_params)
    @team.save
    respond_with(@team)
  end

  def update
    @team.update(team_params)
    respond_with(@team)
  end

  def destroy
    @team.destroy
    respond_with(@team)
  end

  private
    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:name, :article_id, :wins, :loses)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Player" %><br>
    <%= f.select(:player_id, @players.collect {|d| [ d.name, d.id ] }.sort, {:include_blank => 'Please select a player'}) %>
  </div>
  <div>and/or</div>
  <div class="field">
    <%= f.label "Team" %><br>
    <%= f.select(:team_id, @teams.collect {|d| [ d.name, d.id ] }.sort, {:include_blank => 'Please select a team'}) %>
  </div>

  <hr>

  <div class="field">
    <%= f.text_area :part1, class: "text-area", placeholder: "Article Part 1" %>
  </div>

  <div class="field">
    <%= f.label "Question 1" %><br>
    <%= f.text_field :quiz1, class: "form-control", placeholder: "Question 1" %>
  </div>
  <div class="field">
      &bull; <%= f.label "Question 1 Correct Answer" %><br>
      <%= f.text_field :q1answer, class: "form-control", placeholder: "Type CORRECT answer here" %>
  </div>
  <div class="field">
      &bull; <%= f.label "Question 1 Incorrect Answer" %><br>
      <%= f.text_field :q1wrong1, class: "form-control", placeholder: "Type INCORRECT answer here" %>
  </div>
  <div class="field">
      &bull; <%= f.label "Question 1 Incorrect Answer" %><br>
      <%= f.text_field :q1wrong2, class: "form-control", placeholder: "Type INCORRECT answer here" %>
  </div>
  <hr style="height:2px;background-color:gray">
  <div class="field">
    <%= f.text_area :part2, class: "text-area", placeholder: "Article Part 2" %>
  </div>
  <div class="field">
    <%= f.label "Question 2" %><br>
    <%= f.text_field :quiz2, class: "form-control", placeholder: "Question 2" %>
  </div>
  <div class="field">
    &bull; <%= f.label "Question 2 Correct Answer" %><br>
      <%= f.text_field :q2answer, class: "form-control", placeholder: "Type CORRECT answer here" %>
  </div>
  <div class="field">
    &bull; <%= f.label "Question 2 Incorrect Answer" %><br>
      <%= f.text_field :q2wrong1, class: "form-control", placeholder: "Type INCORRECT answer here" %>
  </div>
  <div class="field">
    &bull; <%= f.label "Question 2 Incorrect Answer" %><br>
      <%= f.text_field :q2wrong2, class: "form-control", placeholder: "Type INCORRECT answer here" %>
  </div>
  <hr style="height:2px;background-color:gray">
  <div class="field">
    <%= f.text_area :part3, class: "text-area", placeholder: "Article Part 3" %>
  </div>
  <div class="field">
    <%= f.label "Question 3" %><br>
    <%= f.text_field :quiz3, class: "form-control", placeholder: "Question 3" %>
  </div>
  <div class="field">
    &bull; <%= f.label "Question 3 Correct Answer" %><br>
      <%= f.text_field :q3answer, class: "form-control", placeholder: "Type CORRECT answer here" %>
  </div>
  <div class="field">
    &bull; <%= f.label "Question 3 Incorrect Answer" %><br>
      <%= f.text_field :q3wrong1, class: "form-control", placeholder: "Type INCORRECT answer here" %>
  </div>
  <div class="field">
    &bull; <%= f.label "Question 3 Incorrect Answer" %><br>
      <%= f.text_field :q3wrong2, class: "form-control", placeholder: "Type INCORRECT answer here" %>
  </div>
  <hr style="height:2px;background-color:gray">
  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_field :video, class: "form-control", placeholder: "Paste Embed Code Here" %>
  </div>

  <hr>

  <div class="field">
    <%= f.check_box :publishable %> <%= f.label :publishable %>
  </div>

  <hr style="height:2px;background-color:gray">

  <div>
    <%= f.submit "Create Article", class: "btn btn-success" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div>
	<br />
  <br />
  <br />
  <br />
  <div class="row">
    <div class="col-md-8 col-md-offset-2 text-box">
			<h1>Editing article</h1>

			<%= render 'form' %>

			<%= link_to 'Show', @article %> |
			<%= link_to 'Back', articles_path %>
		</div>
	</div>
</div>

app/views/articles/editor_index.html.erb
<% @articles.each do |article| %>
	<div class="editor-article">
		<div>
			<% if article.player != nil %>
				<h3>
					<%= article.player.name %>
				</h3>
			<% elsif article.team != nil %>
				<h3>
					<%= article.team.name %>
				</h3>
			<% end %>
		</div>
		<% if can? :update, article %>
		<div class="edit-or-destroy">
			<%= link_to 'Edit', edit_article_path(article), class: "btn btn-warning" %>   <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
		</div>
		<% end %>
		<div class="article-part-one">
			<p>
				<%= article.part1 %>
			</p>
			<p>
				<%= article.quiz1 %>
			</p>
			<ul>
				<li><strong><%= article.q1answer %></strong></li>
				<li><%= article.q1wrong1 %></li>
				<li><%= article.q1wrong2 %></li>
			</ul>
		</div>
		<div class="article-part-two">
			<p>
				<%= article.part2 %>
			</p>
			<p>
				<%= article.quiz2 %>
			</p>
			<ul>
				<li><strong><%= article.q2answer %></strong></li>
				<li><%= article.q2wrong1 %></li>
				<li><%= article.q2wrong2 %></li>
			</ul>
		</div>
		<div class="article-part-three">
			<p>
				<%= article.part3 %>
			</p>
			<p>
				<%= article.quiz3 %>
			</p>
			<ul>
				<li><strong><%= article.q3answer %></strong></li>
				<li><%= article.q3wrong1 %></li>
				<li><%= article.q3wrong2 %></li>
			</ul>
		</div>
		<div class="article-video">
      <div class="embed-responsive embed-responsive-16by9">
        <%= article.video.html_safe %>
      </div>
		</div>
	</div>
	<br />
	<hr />
	<br />
<% end %>

app/views/articles/index.html.erb
<% if can? :manage, Article %>
  <%= link_to 'New Article', new_article_path, class: "btn btn-success btn-lg" %>
<% end %>
<span class="notice"><%= notice %></span> 
<span class="alert"><%= alert %></span>
<br />
<br />
<div class="row">
  <% @articles.each do |article| %>
    <style>
      .article-bg-<%= article.id%> {
        background: url(<%= article.player.avatar.url %>) no-repeat;
        background-size: 100% 100%;
      }
    </style>
    <div class="col-md-4 bottom-space">
      <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
        <div class="flipper">
          <div class="front article-bg-<%= article.id %>">
            <span>
              <h3><%= article.player.name %></h3>
            </span>
          </div>
          <div class="back article-bg-<%= article.id %>">
            <div class="shadebox">
              <span>
                <%= article.part1[0..30] %>...<br />
                <%= link_to 'Read More', article, class: "btn btn-primary" %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br />
<br />
<br />
<br />

app/views/articles/new.html.erb
<div>
	<br />
  <br />
  <br />
  <br />
  <div class="row">
    <div class="col-md-8 col-md-offset-2 text-box">
			<h1>New Article</h1>

			<%= render 'form' %>

			<%= link_to 'Back', articles_path %>
		</div>
	</div>
	<br />
  <br />
  <br />
  <br />
</div>

app/views/articles/show.html.erb
<div class="article-container">
  <div class="part-one">
    <div class="article-title">
      <h1><%= @article.player.name %></h1>
    </div>
    <p>
      <%= @article.part1 %>
    </p>

    <p>
      <strong>Quiz1:</strong>
      <%= @article.quiz1 %>
    </p>

    <% @randomize_answers1.shuffle.each do |answer| %>
    <% if answer == @article.q1answer %>
      <button id="quiz1" class="btn btn-primary"><%= answer %></button>
      <% else %>
      <button class="wrong btn btn-primary"><%= answer %></button>
      <% end %>
    <% end %>
  </div>

  <div class="part-two">
    <p>
      <strong>Part2:</strong>
      <%= @article.part2 %>
    </p>

    <p>
      <strong>Quiz2:</strong>
      <%= @article.quiz2 %>
    </p>

    <% @randomize_answers2.shuffle.each do |answer| %>
    <% if answer == @article.q2answer %>
      <button id="quiz2" class="btn btn-primary"><%= answer %></button>
      <% else %>
      <button class="wrong btn btn-primary"><%= answer %></button>
      <% end %>
    <% end %>
  </div>

  <div class="part-three">
    <p>
      <strong>Part3:</strong>
      <%= @article.part3 %>
    </p>

    <p>
      <strong>Quiz3:</strong>
      <%= @article.quiz3 %>
    </p>

    <% @randomize_answers3.shuffle.each do |answer| %>
    <% if answer == @article.q3answer %>
      <button id="quiz3" class="btn btn-primary"><%= answer %></button>
      <% else %>
      <button class="wrong btn btn-primary"><%= answer %></button>
      <% end %>
    <% end %>
  </div>

  <div class="video">
      <div class="embed-responsive embed-responsive-16by9">
        <%= @article.video.html_safe %>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YayaSoccer</title>
  <!-- Stylesheets-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <!-- JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application' %>
  
  <%= csrf_meta_tags %>
</head>
<body id="background">

<% if user_signed_in? %>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Yaya Soccer", root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse">
          <% if can? :update, :all %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Articles", editor_index_path %></li>
            <li><%= link_to "Players", players_path %></li>
            <li><%= link_to "Teams", teams_path %></li>
          </ul>
          <% end %>
        <div class="nav navbar-right">
          Hi, <%= current_user.name %> | <%= link_to "Edit My Profile", edit_user_registration_path %> | 
          <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        </div>
      </div>
    </div>
  </nav>
<% end %>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
    <% if @teams != nil %>  
      <%= f.select(:team_id, @teams.collect {|d| [ d.name, d.id ] }.sort, {:include_blank => 'Please select a team'}) %>
    <% end %>
  </div>

  <div class="field">
    <%= f.label "Attach Player Photo" %>
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :goals %><br>
    <%= f.number_field :goals %>
  </div>
  <p></p>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<div>
  <br />
  <br />
  <br />
  <br />
  <div class="row">
    <div class="col-md-4 col-md-offset-4 text-box">
			<h1>Editing player</h1>

			<%= render 'form' %>

			<%= link_to 'Show', @player %> |
			<%= link_to 'Back', players_path %>
		</div>
	</div>
</div>

app/views/players/index.html.erb
<% if can? :update, :all %>
<div class="players-page">
  <h1>Listing Players</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Team</th>
        <th>Goals</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @players.each do |player| %>
        <tr>
          <td><%= player.name %></td>
          <td><%= player.team.name %></td>
          <td><%= player.goals %></td>
          <td><%= link_to 'Show', player %></td>
          <td><%= link_to 'Edit', edit_player_path(player) %></td>
          <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Player', new_player_path %>
</div>
<% else %>
  <div class="players-page not-allowed">
    <p>Sorry, you're not allowed here :-(</p>
  </div>
<% end %>

app/views/players/new.html.erb
<div>
  <br />
  <br />
  <br />
  <br />
  <div class="row">
    <div class="col-md-4 col-md-offset-4 text-box">
			<h1>New player</h1>

			<%= render 'form' %>

			<%= link_to 'Back', players_path %>
		</div>
	</div>
</div>

app/views/players/show.html.erb
<div>
	<br />
  <br />
  <br />
  <br />
  <div class="row">
    <div class="col-md-8 col-md-offset-2 text-box">
			<p id="notice"><%= notice %></p>

			<p>
			  <strong>Name:</strong>
			  <%= @player.name %>
			</p>

			<p>
			  <strong>Team:</strong>
			  <%= @player.team_id %>
			</p>

			<p>
			  <strong>Goals:</strong>
			  <%= @player.goals %>
			</p>

			<%= link_to 'Edit', edit_player_path(@player) %> |
			<%= link_to 'Back', players_path %>
		</div>
	</div>
</div>